language: python

python:
 - 3.6

notifications:
 email:
  on_success: change
  on_failure: change

install:
 - pip install coveralls
 - pip install cookiecutter
 - pip install pycodestyle

script:
 - cookiecutter .
 - cd project
 - . env/bin/activate
 - coverage run --source=. --omit=env/* manage.py test
 - pycodestyle --config=.pycodestylerc ./ --exclude=./env/*,./project/migrations/*

after_success:
 coveralls
