language: python

python:
 - 3.6

notifications:
 email:
  on_success: change
  on_failure: change

install:
 - pip install coveralls
 - pip install cookiecutter
 - pip install pycodestyle

script:
 - cookiecutter .  --no-input
 - cd project
 - docker-compose build
 - docker-compose run web coverage run --source=. --omit=env/* manage.py test
 - docker-compose run web pycodestyle --config=.pycodestylerc .

after_success:
 coveralls
